language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest-cov codecov # Install packages for code coverage report
script:
  - pytest --cov=src tests # Point to the source directory
after_success:
  - codecov # uploades report to codecov.io // codecov = num lines of app code that ran during testing / total num lines of application code * 100